  version: '2'

  services:
    ziravordb_prod:
      container_name: ziravordb_prod
      restart: always  
      image: postgres:12.2
      environment:
        POSTGRES_DB: db_ziravor_prod
        POSTGRES_USER: ziravoruser_prod
        POSTGRES_PASSWORD: ziravorpass_prod
      networks:
        - ziravor-network
      volumes:
          - ziravordata:/var/lib/postgresql/ziravordata/
      
    ziravorweb_prod:
      container_name: ziravorweb_prod
      restart: always  
      build:
        context: .
        dockerfile: Dockerfile.prod
      command: gunicorn config.wsgi:application --bind 0.0.0.0:2020
      volumes:
        - static_volume_ziravor:/home/app/web/static
        - media_volume_ziravor:/home/app/web/media
      networks:
        - ziravor-network
      depends_on: 
        - ziravordb_prod
      ports:
        - "2020:2020"
      env_file: 
        - ./.env.prod

    ziravornginx:
      container_name: ziravor-nginx
      restart: always
      build: ./nginx
      volumes:
        - static_volume_ziravor:/home/app/web/static
        - media_volume_ziravor:/home/app/web/media
      ports:
        - "4040:4040"
      networks:
        - ziravor-network
      depends_on:
        - ziravorweb_prod
        
  volumes:
    ziravordata:
    static_volume_ziravor:
    media_volume_ziravor:

  networks:
    ziravor-network:
      driver: bridge